import type { Metadata } from "next";
import { SectionPage } from "@/components/layout/section-page";
import { KeyTopology } from "@/components/content/key-topology";
import { ProtocolTable } from "@/components/content/protocol-table";
import { KeyLabel } from "@/components/ui/key-label";

export const metadata: Metadata = {
  title: "Theory",
  description:
    "Theory of key distribution using a trusted third party: KDC, long-term keys, session keys, tickets, authentication and freshness.",
};

export default function TheoryPage() {
  return (
    <SectionPage slug="theory">
      <div className="prose-lab">
        <p>
          Symmetric ciphers such as AES are fast and secure, but they have one basic requirement: both parties must
          already hold the same secret key. Getting that key to both parties safely, the <strong>key distribution
          problem</strong>, is the subject of this experiment.
        </p>

        <h2>Trusted Third Party</h2>
        <p>
          A <strong>Trusted Third Party (TTP)</strong> is an entity that two communicating parties both trust to behave
          honestly and to keep their secrets. Instead of every pair of users arranging a secret between themselves, each
          user establishes trust once, with the TTP, and the TTP helps any two users set up a secure channel when they
          need one.
        </p>

        <h2>Key Distribution Center (KDC)</h2>
        <p>
          A <strong>Key Distribution Center</strong> is a TTP whose job is to create and hand out symmetric keys. Every
          registered user shares one secret key with the KDC. When two users wish to talk, the KDC generates a new key for
          them and delivers it to each, protected under that user&apos;s own secret key.
        </p>

        <h3>Why is a KDC needed?</h3>
        <p>
          If <em>n</em> users each need a private channel with every other user, they need one key per pair:{" "}
          <code>n(n−1)/2</code> keys in total. For 1,000 users that is 499,500 keys, each of which must be delivered
          securely and stored by both its owners. With a KDC, each user stores a single key, so only <code>n</code> keys
          exist in total, and adding a new user means setting up just one new key.
        </p>

        <KeyTopology />

        <h2>Long-term keys and session keys</h2>
        <ul>
          <li>
            <strong>Long-term key (master key):</strong> a secret shared between one user and the KDC, set up once when
            the user registers (for example, in person or over a separate secure channel). Alice&apos;s is{" "}
            <KeyLabel id="A" /> and Bob&apos;s is <KeyLabel id="B" />. Long-term keys are used only to protect key
            distribution messages, never bulk data, so that they are exposed as little as possible.
          </li>
          <li>
            <strong>Session key:</strong> a fresh random key, <KeyLabel id="AB" />, generated by the KDC for one
            conversation between Alice and Bob and discarded afterwards. If a session key is ever compromised, only that
            one session is affected, not the user&apos;s long-term key or other sessions.
          </li>
        </ul>

        <h2>The participants</h2>
        <ul>
          <li>
            <strong>Alice</strong>, the initiator, wants to communicate securely with Bob. Alice knows only{" "}
            <KeyLabel id="A" />.
          </li>
          <li>
            <strong>Bob</strong>, the responder. Bob knows only <KeyLabel id="B" />.
          </li>
          <li>
            <strong>KDC</strong>, the trusted server. It knows both <KeyLabel id="A" /> and <KeyLabel id="B" />, and
            generates <KeyLabel id="AB" />.
          </li>
        </ul>
        <p>
          The network between them is assumed to be insecure: an attacker can read, modify, replay or inject messages.
        </p>

        <h2>Tickets</h2>
        <p>
          The KDC could send <KeyLabel id="AB" /> to Bob directly, but it is simpler for it to answer only the user who
          asked. So the KDC places the session key for Bob inside a <strong>ticket</strong>, encrypted under{" "}
          <KeyLabel id="B" />, and gives the ticket to Alice. Alice cannot read or usefully change the ticket, without
          knowing <KeyLabel id="B" />; Alice simply forwards it to Bob, who decrypts it.
        </p>

        <h2>Authentication and confidentiality</h2>
        <ul>
          <li>
            <strong>Confidentiality:</strong> <KeyLabel id="AB" /> only ever travels encrypted under <KeyLabel id="A" />{" "}
            or <KeyLabel id="B" />, so an eavesdropper never sees it. Afterwards, the conversation is encrypted under{" "}
            <KeyLabel id="AB" />.
          </li>
          <li>
            <strong>Authentication:</strong> only the KDC (besides Alice) knows <KeyLabel id="A" />. When Alice
            successfully decrypts a well-formed reply, Alice knows it was produced by the KDC. Likewise, a ticket that
            decrypts correctly under <KeyLabel id="B" /> convinces Bob that the KDC created it, and the name inside tells
            Bob who is on the other end.
          </li>
          <li>
            <strong>Freshness:</strong> Alice includes a random <strong>nonce</strong> N₁ in the request; seeing N₁ in
            the reply proves the reply is new, not a recording of an old one. The ticket carries a{" "}
            <strong>timestamp</strong> T so that Bob can reject old tickets that an attacker might replay.
          </li>
        </ul>
        <p>
          The simulation uses <strong>AES-GCM</strong>, an authenticated encryption mode. Besides hiding the content,
          AES-GCM attaches a 128-bit authentication tag; if even one bit of the ciphertext is changed, or the wrong key is
          used, decryption fails instead of returning garbage. This makes the &ldquo;decrypts correctly&rdquo; checks
          above dependable.
        </p>

        <h2>Basic message flow</h2>
        <p>
          The notation <code>E(K, X)</code> means &ldquo;X encrypted under key K&rdquo; and <code>‖</code> means
          concatenation (here, the fields are packed together into one structured message before encryption).
        </p>
        <ProtocolTable />
        <ol>
          <li>Alice tells the KDC who is asking, who the session is with, and a fresh nonce N₁.</li>
          <li>
            The KDC generates <KeyLabel id="AB" />, builds the ticket for Bob under <KeyLabel id="B" />, and returns
            everything to Alice under <KeyLabel id="A" />.
          </li>
          <li>
            Alice decrypts the reply, checks N₁ and Bob&apos;s name, keeps <KeyLabel id="AB" />, and forwards the ticket
            to Bob.
          </li>
          <li>
            Bob decrypts the ticket, checks the timestamp, and obtains <KeyLabel id="AB" />. Both parties now share the
            session key and can exchange encrypted messages.
          </li>
        </ol>

        <h2>Scope of this experiment</h2>
        <p>
          The protocol here is a simplified, educational variant of the symmetric-key{" "}
          <strong>Needham–Schroeder</strong> protocol (1978), with a timestamp added to the ticket as proposed by Denning
          and Sacco to prevent replay of old tickets. It is not Kerberos, and it omits steps a deployed system would need,
          such as Bob confirming that Alice actually holds <KeyLabel id="AB" /> (a challenge–response handshake), clock
          synchronisation, ticket lifetimes and key revocation. It does, however, capture the central idea on which
          Kerberos and similar systems are built.
        </p>
      </div>
    </SectionPage>
  );
}
