import type { Metadata } from "next";
import { SectionPage } from "@/components/layout/section-page";
import { KeyTopology } from "@/components/content/key-topology";
import { ProtocolTable } from "@/components/content/protocol-table";
import { KeyLabel } from "@/components/ui/key-label";

export const metadata: Metadata = {
  title: "Theory",
  description:
    "Theory of key distribution using a trusted third party: KDC, long-term keys, session keys, tickets, authentication and freshness.",
};

export default function TheoryPage() {
  return (
    <SectionPage slug="theory">
      <div className="prose-lab">
        <p>
          Symmetric ciphers such as AES require both parties to already hold the same secret key. Delivering that key
          safely is the <strong>key distribution problem</strong>.
        </p>

        <h2>Trusted Third Party and KDC</h2>
        <p>
          A <strong>Trusted Third Party (TTP)</strong> is an entity both communicating parties trust. A{" "}
          <strong>Key Distribution Center (KDC)</strong> is a TTP that creates and hands out symmetric keys. Every user
          shares one secret key with the KDC; when two users want to talk, the KDC generates a new key for them.
        </p>
        <p>
          Without a KDC, <em>n</em> users need <code>n(n−1)/2</code> pairwise keys. With a KDC, each user stores just
          one key, so only <code>n</code> keys are needed.
        </p>

        <KeyTopology />

        <h2>Long-term keys and session keys</h2>
        <ul>
          <li>
            <strong>Long-term key:</strong> shared between one user and the KDC, set up once at registration:{" "}
            <KeyLabel id="A" /> for Alice, <KeyLabel id="B" /> for Bob. Used only to protect key distribution messages.
          </li>
          <li>
            <strong>Session key:</strong> a fresh random key <KeyLabel id="AB" /> generated by the KDC for one
            conversation and then discarded. If it leaks, only that session is affected.
          </li>
        </ul>

        <h2>Tickets</h2>
        <p>
          The KDC puts the session key for Bob inside a <strong>ticket</strong> encrypted under <KeyLabel id="B" /> and
          gives it to Alice. Alice cannot read the ticket and simply forwards it to Bob, who decrypts it.
        </p>

        <h2>Security properties</h2>
        <ul>
          <li>
            <strong>Confidentiality:</strong> <KeyLabel id="AB" /> only travels encrypted under <KeyLabel id="A" /> or{" "}
            <KeyLabel id="B" />, so an eavesdropper never sees it.
          </li>
          <li>
            <strong>Authentication:</strong> a message that decrypts correctly under a user&apos;s long-term key must
            have come from the KDC, the only other holder of that key.
          </li>
          <li>
            <strong>Freshness:</strong> Alice&apos;s random nonce N₁ and the ticket&apos;s timestamp T let the parties
            reject replayed old messages.
          </li>
        </ul>
        <p>
          The simulation uses <strong>AES-GCM</strong>, which adds an authentication tag: if the ciphertext is modified
          or the wrong key is used, decryption fails.
        </p>

        <h2>Message flow</h2>
        <p>
          <code>E(K, X)</code> means &ldquo;X encrypted under key K&rdquo; and <code>‖</code> means concatenation.
        </p>
        <ProtocolTable />

        <p className="text-sm text-muted">
          This is a simplified, educational variant of the symmetric-key Needham–Schroeder protocol, with a timestamp in
          the ticket. It is not Kerberos, but it shows the central idea Kerberos is built on.
        </p>
      </div>
    </SectionPage>
  );
}
