/** User-editable simulation settings. */
export interface SimConfig {
  aliceName: string;
  bobName: string;
  message: string;
  /** Long-term key shared by Alice and the KDC (64 hex chars = 256 bits). */
  aliceKeyHex: string;
  /** Long-term key shared by Bob and the KDC (64 hex chars = 256 bits). */
  bobKeyHex: string;
  /** Flip one bit of the ticket while Alice forwards it to Bob. */
  tamperTicket: boolean;
}

export type ConfigField = "aliceName" | "bobName" | "message" | "aliceKeyHex" | "bobKeyHex";
export type ConfigErrors = Partial<Record<ConfigField, string>>;

/** Output of one AES-GCM encryption, hex encoded for display/transport. */
export interface CipherBlob {
  /** 96-bit initialisation vector. */
  iv: string;
  /** Ciphertext followed by the 128-bit authentication tag. */
  ciphertext: string;
}

/** Step 1: Alice → KDC (sent in the clear). */
export interface SessionRequest {
  type: "REQUEST";
  initiator: string;
  responder: string;
  nonce: string;
}

/** Contents of the ticket, readable only with K_B. */
export interface TicketPlaintext {
  initiator: string;
  sessionKey: string;
  timestamp: number;
}

/** Contents of the KDC → Alice response, readable only with K_A. */
export interface KdcResponsePlaintext {
  nonce: string;
  responder: string;
  sessionKey: string;
  ticket: CipherBlob;
}

export interface AliceView {
  sessionKeyHex: string;
  ticket: CipherBlob;
  nonceMatches: boolean;
  responderMatches: boolean;
}

export type BobView =
  | {
      accepted: true;
      initiator: string;
      sessionKeyHex: string;
      timestamp: number;
      ageMs: number;
    }
  | {
      accepted: false;
      reason: string;
    };

export interface SecureMessage {
  plaintext: string;
  encrypted: CipherBlob;
  decrypted: string;
}

/** Everything observable that the protocol has produced so far. */
export interface ProtocolData {
  request?: SessionRequest;
  sessionKeyHex?: string;
  ticketPlaintext?: TicketPlaintext;
  ticket?: CipherBlob;
  responsePlaintext?: KdcResponsePlaintext;
  response?: CipherBlob;
  alice?: AliceView;
  forwardedTicket?: CipherBlob;
  ticketTampered?: boolean;
  bob?: BobView;
  message?: SecureMessage;
}

/** Key material held by each party. Never rendered directly. */
export interface ProtocolSecrets {
  /** K_A as held by Alice and by the KDC (same key). */
  kA: CryptoKey;
  /** K_B as held by Bob and by the KDC (same key). */
  kB: CryptoKey;
  /** K_AB as generated by the KDC. */
  kdcSessionKey?: CryptoKey;
  /** K_AB as recovered by Alice from the KDC response. */
  aliceSessionKey?: CryptoKey;
  /** K_AB as recovered by Bob from the ticket. */
  bobSessionKey?: CryptoKey;
}

export type StepNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

/**
 * Protocol phase reached after N completed steps.
 * Index = number of completed steps.
 */
export const PHASES = [
  "IDLE",
  "REQUEST_SENT",
  "SESSION_KEY_GENERATED",
  "TICKET_CREATED",
  "KDC_RESPONSE_SENT",
  "ALICE_DECRYPTED",
  "BOB_DECRYPTED",
  "SESSION_ESTABLISHED",
  "COMPLETE",
] as const;

export type Phase = (typeof PHASES)[number];

export type SimStatus =
  /** Settings are being edited; nothing has run. */
  | "configuring"
  /** A step's cryptographic work is in progress. */
  | "busy"
  /** Waiting for the student to press Next. */
  | "running"
  /** A party rejected a message (e.g. tampered ticket); the run cannot continue. */
  | "aborted"
  /** An unexpected failure (Web Crypto error, etc.). */
  | "error"
  /** All steps finished. */
  | "complete";

export interface SimState {
  status: SimStatus;
  /** Number of protocol steps that have completed (0–8). */
  completed: number;
  /** Step currently displayed (1..completed), or 0 before starting. */
  view: number;
  /** Configuration locked in for the current run. */
  config: SimConfig | null;
  data: ProtocolData;
  /** Incremented on each start/restart so stale async results are ignored. */
  runId: number;
  error: string | null;
}
